{
    'name': 'CoordOS Shell',
    'version': '1.0',
    'summary': 'CoordOS UI Shell for SPU / Trip',
    'author': 'CoordOS',
    'depends': ['base', 'web'],
    'data': [
        'security/coordos_groups.xml',
        'security/ir.model.access.csv',
        'data/trip_cron.xml',
        'data/template_config_data.xml',
        'data/parser_profile_data.xml',
        'views/project_views.xml',
        'views/project_import_views.xml',
        'views/config_views.xml',
        'views/pile_views.xml',
        'views/bridge_table_upload_views.xml',
        'views/spu_views.xml',
        'views/trip_views.xml',
        'views/qa_views.xml',
        'reports/pile_report.xml',
    ],
    'installable': True,
}
